### ISSUE TITLE
TypeError: jsnums.isExactInteger is not a function

### ISSUE THREAD

**Issue by Emmay** [brownplt/pyret-lang#535]
I'm receiving this error in a few different programs:
https://code.pyret.org/editor#share=0B9rKDmABYlJVY01HTXc1NUx0b0U&v=v0.5r1415
https://code.pyret.org/editor#share=0B9rKDmABYlJVYUh2ZldVQXJ5VkE&v=v0.5r1415
and 
https://code.pyret.org/editor#share=0B9rKDmABYlJVVU4tV1VySHVZaWs&v=v0.5r1415
when I try to call the draw-car function on one of the pre-defined Cars

**Comment by dyoo** [comment]
Possible interaction from:  https://github.com/brownplt/pyret-lang/commit/fa07a807173037613de3a0253c9f89aa9d089753

I look at `src/js/trove/image.js`, and there appear to be two definitions of checkNaturalNumber, one with the correction from the commit above,

https://github.com/brownplt/pyret-lang/blob/master/src/js/trove/image.js#L168

but what appears to be another copy of the function:

https://github.com/brownplt/pyret-lang/blob/master/src/js/trove/image.js#L217

**Comment by dyoo** [comment]
Note: this issue is also affecting the front page program "Play 2048".

Executing: https://code.pyret.org/editor#share=0B32bNEogmncOMTg5T2plV19LX0k

responds with the following error message:

An unexpected error occurred: TypeError: jsnums.isExactInteger is not a function

**Comment by dyoo** [comment]
This appears to be a copy of the issue Ben brought up in Issue 527.

**Comment by jpolitz** [comment]
Yeah, fixed now, and pushed out soon.  Sorry about that, bad merge and lack of a test for that.

**Comment by jpolitz** [comment]
Closed by https://github.com/brownplt/pyret-lang/commit/158dfa678b9da6a81df01d6f89d6e012ea3964c3
